### ISSUE TITLE
Match group information

### ISSUE THREAD

**Issue by Limeth** [artemanufrij/regextester#4]
It would be great if the application also displayed which regex groups matched what parts of the test string.

**Comment by artemanufrij** [comment]
@Limeth have you an application / website witch does it?

**Comment by Limeth** [comment]
For example, Regex101 has such a feature implemented: https://regex101.com/r/XSDPTm/1

**Comment by artemanufrij** [comment]
@Limeth now I have to fix colors. I guess I can finish it tomorrow.

![bildschirmfoto von 2017-09-12 22 08 47](https://user-images.githubusercontent.com/16517095/30345848-0fafd0b0-9807-11e7-9f67-2a94b6d58b72.png)

**Comment by artemanufrij** [comment]
@Limeth could you test current master branch please?

**Comment by Limeth** [comment]
Sure. How can I build it?

**Comment by artemanufrij** [comment]
@Limeth here is a documentation:
https://github.com/artemanufrij/regextester/blob/master/README.md#hot-to-build-from-github

**Comment by Limeth** [comment]
I am getting an error when trying to build it using the instructions:
```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
CMake Error at CMakeLists.txt:32 (include):
  include could not find load file:

    ValaPrecompile


CMake Error at CMakeLists.txt:33 (find_package):
  By not providing "FindVala.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vala", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vala" with any of
  the following names:

    ValaConfig.cmake
    vala-config.cmake

  Add the installation prefix of "Vala" to CMAKE_PREFIX_PATH or set
  "Vala_DIR" to a directory containing one of the above files.  If "Vala"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/limeth/workspace/vala/regextester/build/CMakeFiles/CMakeOutput.log".
```

**Comment by artemanufrij** [comment]
@Limeth install elementary sdk and try it again please:

`sudo apt install elementary-sdk`

**Comment by Limeth** [comment]
It looks like it's working as intended! Thank you for adding this feature. :tada:

**Comment by artemanufrij** [comment]
@Limeth thank you for testing.
